### PR TITLE
Use PreparedStatement to improve the performance

### PR DESCRIPTION
**Pull request by muga**
This PR replaces `Statement#executeQuery` call in the plugin with `PreparedStatement#executeQuery` to improve the performance.

Reference: http://qiita.com/sonots/items/a70482d29862de87624d

### CODE REVIEW

**Comment by muga** [comment]
@dmikurube Please take a look when you have time.

**Comment by sonots** [comment]
I re-evaluated the performance ( http://qiita.com/sonots/items/a70482d29862de87624d ) with this branch. It became very fast.

Before:

| plugin           | opertor                   | Time took |
|-----------------------|------------------------|--------------|
| embulk-filter-calcite | String = operator | 7m27.246s |
| embulk-filter-calcite | String LIKE operator | 7m37.213s |
| embulk-filter-calcite | String SIMILAR TO (REGEXP) operator |  |
| embulk-filter-calcite | Column copy | 6m8.781s |

After:

| plugin           | opertor                   | Time took |
|-----------------------|------------------------|--------------|
| embulk-filter-calcite | String = operator | 0m27.169s |
| embulk-filter-calcite | String LIKE operator | 0m31.449s |
| embulk-filter-calcite | String SIMILAR TO (REGEXP) operator | 0m30.002s |
| embulk-filter-calcite | Column copy | 0m27.446s |

**Comment by muga** [comment]
@sonots Wow, thank you for evaluating the performance. Good to hear that.

(I felt that the bootstrap cost of the plugin is a little bit high instead of others like row filter but, it might be ignorable for large-sized data ingestion.)

**Review by dmikurube — APPROVED** [review]
lgtm!

**Comment by muga** [comment]
@dmikurube Thank you for reviewing. Merging.

**Pull request merged**
